### ISSUE TITLE
develop fails cargo test --workspace: no_std Vec scope error, several property-test compile errors, and 8 dead issuer-registry event tests

### ISSUE THREAD

**Issue by dikachim060-wq** [veridatum-labs/earnproof-contracts#118]
## Description

Found while working on #99 (event emission tests, already resolved separately — see that issue's comment thread). `cargo test --workspace` fails on a clean `develop` checkout, independent of anything in #99's own scope. Filing separately since these are unrelated compile errors spread across several crates.

## 1. `packages/shared/src/lib.rs` — `Vec`/`vec!` not in scope under `#![no_std]`

```
error: cannot find macro `vec` in this scope
   --> packages/shared/src/lib.rs:245:35
error[E0425]: cannot find type `Vec` in this scope
   --> packages/shared/src/lib.rs:190:28
error[E0425]: cannot find type `Vec` in this scope
   --> packages/shared/src/lib.rs:231:31
error[E0425]: cannot find type `Vec` in this scope
   --> packages/shared/src/lib.rs:252:19
```

The crate is `#![no_std]` (line 1) with no `extern crate alloc;` / `use alloc::vec::Vec;` (or `soroban_sdk::Vec`, if that's the intended type instead of `alloc::vec::Vec`). This blocks `cargo test --workspace` entirely, since `earnproof-shared` is a dependency of the contract crates.

## 2. `tests/property`, `tests/budgets` (or similar) — several distinct compile errors

```
error[E0599]: no method named `set_timestamp` found for struct `soroban_sdk::ledger::Ledger` in the current scope
help: trait `Ledger` which provides `set_timestamp` is implemented but not in scope; perhaps you want to import it
  | use soroban_sdk::testutils::Ledger;
(appears twice)

error[E0308]: mismatched types
  --> (try_op helper, `env: &Env` parameter)

error[E0382]: borrow of moved value: `status`
  | prop_assert_eq!(record.status, status.clone());  (needs .clone())

error[E0382]: borrow of moved value: `current_admin`
  | prop_assert_eq!(client.get_admin(), current_admin.clone());  (needs .clone())

error[E0382]: borrow of moved value: `admin`
  | let mut current_admin = admin.clone();  (needs .clone())

error[E0599]: no method named `clone` found for struct `protocol_config::ProtocolConfigContractClient<'a>` in the current scope
  | let pc = _pc.clone();  (ProtocolConfigContractClient needs #[derive(Clone)] or similar)

error[E0284]: type annotations needed
```

All look like straightforward fixes (a missing trait import, a few missing `.clone()` calls, a missing `#[derive(Clone)]`), but I didn't want to guess at each one's correct fix without being sure I understood the intent of the surrounding property-based tests.

## 3. `contracts/issuer-registry/src/lib.rs` — event tests declared but never actually run

```
warning: cannot test inner items
   --> contracts/issuer-registry/src/lib.rs:770:5 (and 7 more at similar lines)
warning: function `register_issuer_emits_one_event` is never used
   --> contracts/issuer-registry/src/lib.rs:771:8 (and 7 more)
```

8 functions (`register_issuer_emits_one_event`, `register_issuer_failure_emits_no_success_event`, `update_issuer_emits_one_event`, `update_revoked_issuer_emits_no_event`, `suspend_issuer_emits_one_event`, `reactivate_issuer_emits_one_event`, `revoke_issuer_emits_one_event`, `rotate_address_emits_one_event`, `rotate_revoked_issuer_address_emits_no_event`, `each_mutation_emits_exactly_one_event`) are marked `#[test]` but declared inside a module that isn't gated with `#[cfg(test)] mod test { ... }` the way Rust's test harness expects ("cannot test inner items") — so they compile but **never actually execute** as part of `cargo test`. This is a real gap: someone wrote event-emission tests for `issuer-registry` specifically, and they silently don't run. (Note: `tests/events/` — the `event-tests` crate — already covers the same ground for `issuer-registry` and does run correctly; this is a separate, seemingly-abandoned/broken set of tests living directly in the contract crate itself.)

## Reproduction

```
git checkout develop
cargo test --workspace
```

(Also requires the fix from PR <link to the brace-fix PR once opened> to get past an unrelated syntax error in `contracts/proof-registry/src/lib.rs` first.)

## Impact

Anyone branching off `develop` inherits a workspace that doesn't build its own test suite, and the 8 `issuer-registry` event tests mentioned in point 3 have presumably never actually run in CI, since Rust silently skips inner test items rather than failing the build over them.

I did not attempt any of these fixes myself — all are outside #99's scope, and several (the property-test `.clone()` fixes, the `no_std` `Vec` import) would benefit from a maintainer's confirmation of intended behavior before changing.

**Comment by dikachim060-wq** [comment]
Additional finding, surfaced only once the stray-brace syntax error (fixed in the linked PR) stopped masking it:

```
error[E0599]: no method named `clone` found for struct `protocol_config::ProtocolConfigContractClient<'a>` in the current scope
   --> contracts/proof-registry/src/lib.rs:731:22
    |
731 |         let pc = _pc.clone();

error[E0284]: type annotations needed
   --> contracts/proof-registry/src/lib.rs:849:49
    |
849 |             env.storage().persistent().get::<_, _>(&DataKey::Proof(proof_id.clone()))
    |                                        ---      ^ cannot infer type of the type parameter `V`
```

`cargo test -p proof-registry` fails on these two even after the brace fix, so `proof-registry`'s own test module has never actually compiled on `develop` — same root cause as point 2 in the description above (a `.clone()`/type-inference gap), just in a third crate. Reproduction: `cargo test -p proof-registry` on `develop` + the brace-fix PR.

**Comment by dunnidev** [comment]
@dunnidev has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hello maintainer, i can fix this issue


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/6b2feb6a-9fd4-415b-95f0-e387ea0a1cd6) or assign @dunnidev to this issue.

**Comment by OmniZlatoon** [comment]
@OmniZlatoon has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> its < than a day, please assign me and see results. my ETA is 4 hours


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/6b2feb6a-9fd4-415b-95f0-e387ea0a1cd6) or assign @OmniZlatoon to this issue.

**Comment by ademolacomfort** [comment]
@ademolacomfort has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hi, I would like to work on this issue


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/6b2feb6a-9fd4-415b-95f0-e387ea0a1cd6) or assign @ademolacomfort to this issue.

**Comment by Oluwasegun6921** [comment]
@Oluwasegun6921 has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hello Maintainer,
> I’m interested in being assigned this issue. I’ll handle the implementation carefully, test the changes, and submit a PR for review.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/6b2feb6a-9fd4-415b-95f0-e387ea0a1cd6) or assign @Oluwasegun6921 to this issue.

**Comment by CollinsKRO** [comment]
@CollinsKRO has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hi, I can fix this kindly assign.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/6b2feb6a-9fd4-415b-95f0-e387ea0a1cd6) or assign @CollinsKRO to this issue.

**Comment by attyolu** [comment]
@attyolu has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Please Maintainer, Assign this issue to me. Im begging 


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/6b2feb6a-9fd4-415b-95f0-e387ea0a1cd6) or assign @attyolu to this issue.

**Comment by Muyideen-js** [comment]
@Muyideen-js has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hi, I can fix this


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/6b2feb6a-9fd4-415b-95f0-e387ea0a1cd6) or assign @Muyideen-js to this issue.

**Comment by babawo96** [comment]
@babawo96 has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> i have reviewed this issue and i would like to work on it


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/6b2feb6a-9fd4-415b-95f0-e387ea0a1cd6) or assign @babawo96 to this issue.
